const path=require('node:path');
const {app,BaseWindow,WebContentsView,ipcMain,session,shell}=require('electron');
const WORKSPACE_URL=process.env.WORKSPACE_URL||'http://127.0.0.1:18999',PARTITION='persist:workspace-web';
let win,workspaceView,webVisible=false,activeId=null,nextId=1;const tabs=new Map();
function safeURL(raw){const url=new URL(raw);if(!['http:','https:'].includes(url.protocol))throw Error('Only HTTP and HTTPS pages can open in Workspace');return url.href}
function pageState(tab){const wc=tab.view.webContents;return{id:tab.id,title:wc.getTitle()||'Page',url:wc.getURL()||tab.url||'',active:tab.id===activeId,canGoBack:wc.navigationHistory.canGoBack(),canGoForward:wc.navigationHistory.canGoForward(),loading:wc.isLoading()}}
function emitState(){if(workspaceView&&!workspaceView.webContents.isDestroyed())workspaceView.webContents.send('web:state',{visible:webVisible,tabs:[...tabs.values()].map(pageState),activeId})}
function active(){const tab=tabs.get(activeId);if(!tab)throw Error('No task page is open');return tab}
function layout(){if(!win||!workspaceView)return;const [width,height]=win.getContentSize(),left=webVisible?Math.max(360,Math.min(520,Math.round(width*.34))):width;workspaceView.setBounds({x:0,y:0,width:left,height});for(const tab of tabs.values()){const visible=webVisible&&tab.id===activeId;tab.view.setVisible(visible);if(visible)tab.view.setBounds({x:left,y:0,width:Math.max(1,width-left),height})}}
function wirePage(tab){const wc=tab.view.webContents;wc.setWindowOpenHandler(({url})=>{try{createTab(url,true)}catch{}return{action:'deny'}});wc.on('will-navigate',(event,url)=>{try{safeURL(url)}catch{event.preventDefault()}});for(const event of ['did-navigate','did-navigate-in-page','page-title-updated','did-start-loading','did-stop-loading'])wc.on(event,()=>emitState())}
function createTab(raw,activate=true){const url=safeURL(raw),ses=session.fromPartition(PARTITION,{cache:true}),view=new WebContentsView({webPreferences:{session:ses,contextIsolation:true,nodeIntegration:false,sandbox:true}}),tab={id:String(nextId++),url,view};tabs.set(tab.id,tab);win.contentView.addChildView(view);wirePage(tab);view.webContents.loadURL(url);if(activate){activeId=tab.id;webVisible=true;layout();emitState()}return pageState(tab)}
function closeTab(id){const tab=tabs.get(String(id));if(!tab)return false;win.contentView.removeChildView(tab.view);tab.view.webContents.close();tabs.delete(tab.id);if(activeId===tab.id)activeId=[...tabs.keys()].at(-1)||null;layout();emitState();return true}
function assertWorkspace(event){if(event.sender.id!==workspaceView.webContents.id)throw Error('Web controls are available only to Workspace');if(!event.sender.getURL().startsWith(WORKSPACE_URL))throw Error('Unrecognized Workspace origin')}
function registerIPC(){const handle=(name,fn)=>ipcMain.handle(name,(event,...args)=>{assertWorkspace(event);return fn(...args)});
 handle('web:set-visible',value=>{webVisible=!!value;layout();emitState();return true});
 handle('web:open',url=>{if(!activeId)return createTab(url,true);active().view.webContents.loadURL(safeURL(url));webVisible=true;layout();return pageState(active())});
 handle('web:new-tab',url=>createTab(url,true));handle('web:list-tabs',()=>({visible:webVisible,activeId,tabs:[...tabs.values()].map(pageState)}));
 handle('web:activate',id=>{if(!tabs.has(String(id)))throw Error('Tab not found');activeId=String(id);webVisible=true;layout();emitState();return pageState(active())});handle('web:close',id=>closeTab(id));
 handle('web:back',()=>{const wc=active().view.webContents;if(wc.navigationHistory.canGoBack())wc.navigationHistory.goBack();return true});handle('web:forward',()=>{const wc=active().view.webContents;if(wc.navigationHistory.canGoForward())wc.navigationHistory.goForward();return true});handle('web:reload',()=>{active().view.webContents.reload();return true});
 handle('web:context',async()=>{const wc=active().view.webContents,page=await wc.executeJavaScript("(()=>({title:document.title,url:location.href,selection:String(getSelection?.()?.toString?.()||'').slice(0,20000),text:String(document.body?.innerText||'').slice(0,250000)}))()");return{...page,tabs:[...tabs.values()].map(pageState)}});
 handle('web:screenshot',async()=>{const image=await active().view.webContents.capturePage();return image.toDataURL()});
 handle('web:act',async action=>{const wc=active().view.webContents;if(!action||typeof action!=='object')throw Error('Invalid page action');if(action.kind==='click'){const x=Math.round(action.x),y=Math.round(action.y);wc.sendInputEvent({type:'mouseDown',x,y,button:'left',clickCount:1});wc.sendInputEvent({type:'mouseUp',x,y,button:'left',clickCount:1});return true}if(action.kind==='type'){await wc.insertText(String(action.text||'').slice(0,20000));return true}if(action.kind==='scroll'){wc.sendInputEvent({type:'mouseWheel',x:0,y:0,deltaX:Number(action.deltaX)||0,deltaY:Number(action.deltaY)||0});return true}if(action.kind==='key'){const key=String(action.key||'').slice(0,60);wc.sendInputEvent({type:'keyDown',keyCode:key});wc.sendInputEvent({type:'keyUp',keyCode:key});return true}throw Error('Unsupported page action')});
}
function createWindow(){win=new BaseWindow({width:1440,height:920,title:'Workspace',backgroundColor:'#ffffff'});workspaceView=new WebContentsView({webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.contentView.addChildView(workspaceView);workspaceView.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/i.test(url))shell.openExternal(url);return{action:'deny'}});workspaceView.webContents.loadURL(WORKSPACE_URL);win.on('resize',layout);win.on('closed',()=>{for(const id of [...tabs.keys()])closeTab(id);workspaceView?.webContents.close();workspaceView=null;win=null});layout()}
app.whenReady().then(()=>{const ses=session.fromPartition(PARTITION,{cache:true});ses.setPermissionRequestHandler((_wc,_permission,callback)=>callback(false));ses.setPermissionCheckHandler(()=>false);registerIPC();createWindow()});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(!win)createWindow()});
